---
- name: Check if httpd exists
  ansible.builtin.shell: |
    systemctl status httpd.service
  register: httpd_status
  failed_when: false

- name: Stop httpd if service exists
  ansible.builtin.systemd:
    name: httpd
    state: stopped
  become: yes
  when: httpd_status.rc == 0

- name: Setup tor artifacts dir
  file:
    path: /var/lib/tor/searchies/
    state: directory
    owner: toranon
    group: toranon
    mode: '0700'
  become: yes
    
- name: Setup torrc file
  ansible.builtin.copy:
    dest: /etc/tor/torrc
    content: |
      HiddenServiceDir /var/lib/tor/searchies/
      HiddenServicePort 80 127.0.0.1:8888
    owner: toranon
    group: toranon
    mode: '0644'
  become: yes
    
- name: setup searchies vhost
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d/searchies.conf
    content: |
      <VirtualHost *:80>
          ServerName "{{ proxy_droplet_server_name }}"

          ProxyPreserveHost On
          ProxyPass / http://127.0.0.1:8888/
          ProxyPassReverse / http://127.0.0.1:8888/

          ErrorLog /var/log/httpd/searchies_error.log
          CustomLog /var/log/httpd/searchies_access.log combined
      </VirtualHost>
    owner: root
    group: root
    mode: '0644'
  become: yes 

- name: Reload systemd to apply changes
  ansible.builtin.command:
    cmd: systemctl daemon-reload
  become: yes

- name: start httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started
  become: yes 
    
- name: start tor, whoowhoooooo
  ansible.builtin.systemd:
    name: tor
    enabled: yes
    state: started
  become: yes

- name: establish tor hostname 
  stat:
    path: /var/lib/tor/searchies/hostname
  register: tor_hostname_file
  become: yes
    
- name: does a tor host exist
  command: cat /var/lib/tor/searchies/hostname
  register: tor_hostname_content
  when: tor_hostname_file.stat.exists
  become: yes

- name: set tor hostname fact
  set_fact:
    tor_hostname_uwu: "{{ tor_hostname_content.stdout }}"
  when: tor_hostname_file.stat.exists and tor_hostname_content.stdout != ""
  become: yes
    
- name: print tor host
  debug:
    msg: "Tor hostname: {{ tor_hostname_uwu }}"
  when: tor_hostname_uwu is defined
  become: yes
